// BidPrepSummary.js
// One-tap bid preparation package generated from ProRated address data
import { useState } from "react";
import { BRAND, Stars } from "./UI";
import { getAgeLabel } from "../api/ownershipDetection.js";

const RATING_CATEGORIES = [
  { id: "payment",       label: "Payment History",   icon: "💰", desc: "How reliably this homeowner pays" },
  { id: "access",        label: "Site Access",        icon: "🚗", desc: "Driveway, staging, equipment clearance" },
  { id: "communication", label: "Communication",      icon: "💬", desc: "Responsiveness and clarity" },
  { id: "timeline",      label: "Timeline Respect",   icon: "⏱", desc: "Honoring start dates and decisions" },
  { id: "obstacles",     label: "Obstacles",          icon: "⚠️", desc: "Unexpected issues, scope changes" },
];

const getRiskLevel = (score) => {
  if (!score) return { label: "No data", color: "#94A3B8", bg: "#F8FAFC", icon: "—" };
  if (score >= 4.0) return { label: "Low Risk",      color: "#166534", bg: "#F0FDF4", icon: "✅" };
  if (score >= 3.0) return { label: "Moderate",      color: "#854D0E", bg: "#FFFBEB", icon: "⚠️" };
  return              { label: "High Risk",     color: "#991B1B", bg: "#FFF1F2", icon: "🔴" };
};

const getPaymentRisk = (score) => {
  if (!score) return { label: "Unknown",       color: "#94A3B8", bg: "#F8FAFC",  detail: "No payment history on record" };
  if (score >= 4.5) return { label: "Excellent",    color: "#166534", bg: "#F0FDF4",  detail: "Consistently pays on time" };
  if (score >= 3.5) return { label: "Good",          color: "#166534", bg: "#F0FDF4",  detail: "Generally pays on time" };
  if (score >= 2.5) return { label: "Moderate Risk", color: "#854D0E", bg: "#FFFBEB",  detail: "Some payment delays reported — consider larger deposit" };
  if (score >= 1.5) return { label: "High Risk",     color: "#991B1B", bg: "#FFF1F2",  detail: "Frequent delays reported — require 50%+ deposit upfront" };
  return                    { label: "Very High Risk",color: "#7F1D1D", bg: "#FFF1F2",  detail: "Serious payment issues — proceed with extreme caution" };
};

// Recommendations removed — ProRated informs, contractors decide

export default function BidPrepSummary({ address, onClose }) {
  const [copied, setCopied] = useState(false);

  const reviews    = address.reviews || [];
  const ratings    = address.ratings || {};
  const street     = address.street || "Unknown Address";
  const city       = address.city || "";
  const state      = address.state || "";
  const reviewCount = reviews.length;

  const paymentRisk   = getPaymentRisk(ratings.payment);
  // Work history from reviews
  const workHistory = reviews
    .map(r => ({ trade: r.trade, work: r.work_label || r.workLabel, date: r.date || r.created_at }))
    .filter(r => r.trade)
    .sort((a, b) => new Date(b.date) - new Date(a.date));

  // Unique trades
  const trades = [...new Set(workHistory.map(w => w.trade))].filter(Boolean);

  // Most recent review date
  const mostRecent = reviews.length > 0
    ? reviews.reduce((latest, r) => {
        const d = new Date(r.created_at || r.date || 0);
        return d > latest ? d : latest;
      }, new Date(0))
    : null;

  // Copy summary as text
  const copyText = () => {
    const lines = [
      `📋 BID PREP — ${street}, ${city} ${state}`,
      `Generated by ProRated · ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}`,
      "",
      `PAYMENT RISK     ${paymentRisk.icon || ""} ${paymentRisk.label} — ${paymentRisk.detail}`,
      `SITE ACCESS      ${getRiskLevel(ratings.access).icon} ${getRiskLevel(ratings.access).label}`,
      `COMMUNICATION    ${getRiskLevel(ratings.communication).icon} ${getRiskLevel(ratings.communication).label}`,
      `TIMELINE         ${getRiskLevel(ratings.timeline).icon} ${getRiskLevel(ratings.timeline).label}`,
      `OBSTACLES        ${getRiskLevel(ratings.obstacles).icon} ${getRiskLevel(ratings.obstacles).label}`,
      "",
      trades.length > 0 ? `TRADES ON RECORD ${trades.join(", ")}` : "TRADES ON RECORD No history",
      "",

      "",
      `Based on ${reviewCount} verified trade professional review${reviewCount !== 1 ? "s" : ""} · prorated.app`,
    ];
    navigator.clipboard?.writeText(lines.join("\n"));
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div style={{ position: "fixed", inset: 0, background: "rgba(0,0,0,0.6)", display: "flex", alignItems: "flex-end", justifyContent: "center", zIndex: 1000, fontFamily: "'DM Sans', sans-serif" }}
      onClick={onClose}>
      <div style={{ background: "#fff", borderRadius: "20px 20px 0 0", width: "100%", maxWidth: 560, maxHeight: "90vh", overflowY: "auto", padding: "0 0 2rem" }}
        onClick={e => e.stopPropagation()}>

        {/* Header */}
        <div style={{ background: BRAND.dark, borderRadius: "20px 20px 0 0", padding: "1.25rem 1.25rem 1rem", position: "sticky", top: 0, zIndex: 10 }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 4 }}>
            <div>
              <div style={{ fontSize: 11, color: "#94A3B8", textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 2 }}>📋 Bid Prep Summary</div>
              <div style={{ fontSize: 16, fontWeight: 800, color: "#F8FAFC", lineHeight: 1.2 }}>{street}</div>
              <div style={{ fontSize: 12, color: "#94A3B8" }}>{city}{state ? `, ${state}` : ""}</div>
            </div>
            <button onClick={onClose}
              style={{ background: "rgba(255,255,255,0.1)", border: "none", color: "#F8FAFC", width: 32, height: 32, borderRadius: "50%", fontSize: 18, cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
              ×
            </button>
          </div>
          <div style={{ fontSize: 10, color: "#64748B", marginTop: 6 }}>
            Based on {reviewCount} verified review{reviewCount !== 1 ? "s" : ""} · {new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}
          </div>
        </div>

        <div style={{ padding: "1rem 1.25rem 0" }}>



          {/* Payment Risk — most important */}
          <div style={{ background: paymentRisk.bg, border: `1.5px solid ${paymentRisk.color}30`, borderRadius: 14, padding: "12px 14px", marginBottom: "1rem" }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 6 }}>
              <div style={{ fontSize: 12, fontWeight: 800, color: BRAND.dark }}>💰 Payment Risk</div>
              <span style={{ background: paymentRisk.bg, color: paymentRisk.color, border: `1px solid ${paymentRisk.color}40`, fontSize: 10, fontWeight: 700, padding: "2px 10px", borderRadius: 8 }}>
                {paymentRisk.label}
              </span>
            </div>
            <div style={{ fontSize: 12, color: BRAND.gray, lineHeight: 1.5, marginBottom: ratings.payment ? 8 : 0 }}>
              {paymentRisk.detail}
            </div>
            {ratings.payment > 0 && (
              <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                <div style={{ flex: 1, height: 6, background: "#E2E8F0", borderRadius: 3, overflow: "hidden" }}>
                  <div style={{ height: "100%", width: `${(ratings.payment / 5) * 100}%`, background: paymentRisk.color, borderRadius: 3 }} />
                </div>
                <span style={{ fontSize: 12, fontWeight: 700, color: paymentRisk.color }}>{ratings.payment?.toFixed(1)}/5</span>
              </div>
            )}
          </div>

          {/* Category breakdown */}
          <div style={{ background: "#fff", border: `1px solid ${BRAND.border}`, borderRadius: 14, padding: "12px 14px", marginBottom: "1rem" }}>
            <div style={{ fontSize: 12, fontWeight: 800, color: BRAND.dark, marginBottom: 12 }}>Site Intelligence</div>
            {RATING_CATEGORIES.filter(c => c.id !== "payment").map(cat => {
              const score = ratings[cat.id];
              const risk  = getRiskLevel(score);
              return (
                <div key={cat.id} style={{ marginBottom: 12 }}>
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 4 }}>
                    <div>
                      <span style={{ fontSize: 12, fontWeight: 700, color: BRAND.dark }}>{cat.icon} {cat.label}</span>
                      <div style={{ fontSize: 10, color: BRAND.gray }}>{cat.desc}</div>
                    </div>
                    <div style={{ display: "flex", alignItems: "center", gap: 6, flexShrink: 0 }}>
                      <span style={{ fontSize: 10, color: risk.color, fontWeight: 700 }}>{risk.icon} {risk.label}</span>
                      {score > 0 && <span style={{ fontSize: 12, fontWeight: 800, color: risk.color }}>{score.toFixed(1)}</span>}
                    </div>
                  </div>
                  <div style={{ height: 5, background: "#E2E8F0", borderRadius: 3, overflow: "hidden" }}>
                    <div style={{ height: "100%", width: score ? `${(score / 5) * 100}%` : "0%", background: risk.color, borderRadius: 3, transition: "width 0.4s ease" }} />
                  </div>
                </div>
              );
            })}
          </div>

          {/* Work history */}
          <div style={{ background: "#fff", border: `1px solid ${BRAND.border}`, borderRadius: 14, padding: "12px 14px", marginBottom: "1rem" }}>
            <div style={{ fontSize: 12, fontWeight: 800, color: BRAND.dark, marginBottom: 10 }}>🔨 Work History on Record</div>
            {workHistory.length === 0 ? (
              <div style={{ fontSize: 12, color: BRAND.gray }}>No documented work history yet.</div>
            ) : (
              workHistory.slice(0, 5).map((w, i) => (
                <div key={i} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "6px 0", borderBottom: i < workHistory.slice(0,5).length - 1 ? `1px solid #F1F5F9` : "none" }}>
                  <div>
                    <div style={{ fontSize: 12, fontWeight: 600, color: BRAND.dark, textTransform: "capitalize" }}>{w.trade}</div>
                    {w.work && <div style={{ fontSize: 10, color: BRAND.gray }}>{w.work}</div>}
                  </div>
                  <div style={{ fontSize: 10, color: BRAND.gray, flexShrink: 0 }}>
                    {w.date ? getAgeLabel(w.date) : "—"}
                  </div>
                </div>
              ))
            )}
          </div>

          {/* Data freshness */}
          <div style={{ background: "#F8FAFC", border: `1px solid ${BRAND.border}`, borderRadius: 12, padding: "10px 14px", marginBottom: "1rem", fontSize: 11, color: BRAND.gray, lineHeight: 1.6 }}>
            <strong style={{ color: BRAND.dark }}>Data freshness:</strong>{" "}
            {reviewCount === 0
              ? "No reviews yet — be the first to rate this job site."
              : `${reviewCount} review${reviewCount !== 1 ? "s" : ""} on record.${mostRecent ? ` Most recent: ${getAgeLabel(mostRecent.toISOString())}.` : ""} Scores are age-weighted — recent reviews count more.`
            }
          </div>

          {/* Actions */}
          <div style={{ display: "flex", gap: 10 }}>
            <button onClick={copyText}
              style={{ flex: 1, background: copied ? "#16A34A" : BRAND.dark, color: "#fff", border: "none", padding: "12px", borderRadius: 12, fontSize: 13, fontWeight: 700, cursor: "pointer", fontFamily: "'DM Sans', sans-serif", transition: "background 0.2s" }}>
              {copied ? "✓ Copied to clipboard" : "📋 Copy Summary"}
            </button>
            <button onClick={onClose}
              style={{ flex: 1, background: "#F1F5F9", color: BRAND.gray, border: "none", padding: "12px", borderRadius: 12, fontSize: 13, fontWeight: 600, cursor: "pointer", fontFamily: "'DM Sans', sans-serif" }}>
              Close
            </button>
          </div>

          <div style={{ fontSize: 10, color: "#94A3B8", textAlign: "center", marginTop: 10, lineHeight: 1.5 }}>
  ProRated aggregates peer-sourced data from verified contractors. Scores and information reflect individual contractor experiences and are not the opinion or advice of the ProRated team. All business decisions are solely yours.
          </div>
        </div>
      </div>
    </div>
  );
}
